/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124525-g0c1a1ee12e-20260517"
#endif /* AVUTIL_FFVERSION_H */
